#!/bin/bash
python CleansedMesh_orphan.py &
python CleansedMesh_orphan_0.py &
python CleansedMesh_orphan_1.py &
python CleansedMesh_orphan_2.py &
python CleansedMesh_orphan_3.py &
python CleansedMesh_orphan_4.py &
python CleansedMesh_orphan_5.py &
python CleansedMesh_orphan_6.py &
python CleansedMesh_orphan_7.py &
python CleansedMesh_orphan_8.py &
python CleansedMesh_orphan_9.py &
python CleansedMesh_orphan_10.py &
python CleansedMesh_orphan_11.py &
python CleansedMesh_orphan_12.py &
python CleansedMesh_orphan_13.py &
python CleansedMesh_orphan_14.py &
python CleansedMesh_orphan_15.py &
python CleansedMesh_orphan_16.py &
python CleansedMesh_orphan_17.py &
python CleansedMesh_orphan_18.py &
python CleansedMesh_orphan_19.py &
python CleansedMesh_orphan_20.py &
python CleansedMesh_orphan_21.py &
python CleansedMesh_orphan_22.py &
python CleansedMesh_orphan_23.py &
python CleansedMesh_orphan_24.py &
python CleansedMesh_orphan_25.py &
python CleansedMesh_orphan_26.py &
python CleansedMesh_orphan_27.py &
python CleansedMesh_orphan_28.py &
python CleansedMesh_orphan_29.py &
python CleansedMesh_orphan_30.py &
python CleansedMesh_orphan_31.py &
python CleansedMesh_orphan_32.py &
python CleansedMesh_orphan_33.py &
python CleansedMesh_orphan_34.py &
python CleansedMesh_orphan_35.py &
python CleansedMesh_orphan_36.py &
python CleansedMesh_orphan_37.py &
python CleansedMesh_orphan_38.py &
python CleansedMesh_orphan_39.py &
python CleansedMesh_orphan_40.py &
python CleansedMesh_orphan_41.py &
python CleansedMesh_orphan_42.py &
python CleansedMesh_orphan_43.py &
python CleansedMesh_orphan_44.py &
python CleansedMesh_orphan_45.py &
python CleansedMesh_orphan_46.py &
python CleansedMesh_orphan_47.py &
python CleansedMesh_orphan_48.py &
python CleansedMesh_orphan_49.py &
