#!/bin/bash
python decimation_script_orphans.py &
python decimation_script_orphans_0.py &
python decimation_script_orphans_1.py &
python decimation_script_orphans_2.py &
python decimation_script_orphans_3.py &
python decimation_script_orphans_4.py &
python decimation_script_orphans_5.py &
python decimation_script_orphans_6.py &
python decimation_script_orphans_7.py &
python decimation_script_orphans_8.py &
python decimation_script_orphans_9.py &
python decimation_script_orphans_10.py &
python decimation_script_orphans_11.py &
python decimation_script_orphans_12.py &
python decimation_script_orphans_13.py &
python decimation_script_orphans_14.py &
python decimation_script_orphans_15.py &
python decimation_script_orphans_16.py &
python decimation_script_orphans_17.py &
python decimation_script_orphans_18.py &
python decimation_script_orphans_19.py &
python decimation_script_orphans_20.py &
python decimation_script_orphans_21.py &
python decimation_script_orphans_22.py &
python decimation_script_orphans_23.py &
python decimation_script_orphans_24.py &
python decimation_script_orphans_25.py &
python decimation_script_orphans_26.py &
python decimation_script_orphans_27.py &
python decimation_script_orphans_28.py &
python decimation_script_orphans_29.py &
python decimation_script_orphans_30.py &
python decimation_script_orphans_31.py &
python decimation_script_orphans_32.py &
python decimation_script_orphans_33.py &
python decimation_script_orphans_34.py &
python decimation_script_orphans_35.py &
python decimation_script_orphans_36.py &
python decimation_script_orphans_37.py &
python decimation_script_orphans_38.py &
python decimation_script_orphans_39.py &
python decimation_script_orphans_40.py &
python decimation_script_orphans_41.py &
python decimation_script_orphans_42.py &
python decimation_script_orphans_43.py &
python decimation_script_orphans_44.py &
python decimation_script_orphans_45.py &
python decimation_script_orphans_46.py &
python decimation_script_orphans_47.py &
python decimation_script_orphans_48.py &
python decimation_script_orphans_49.py &
